"""
Example Blender Python Scripts Generated by the MCP Server
These scripts can be run directly in Blender's Python console or script editor
"""

# Example 1: Simple Geometric Shape
example_cube = """
import bpy

# Delete default cube if it exists
if "Cube" in bpy.data.objects:
    bpy.data.objects["Cube"].select_set(True)
    bpy.ops.object.delete()

# Create cube
bpy.ops.mesh.primitive_cube_add(size=2.0, location=(0, 0, 0))
obj = bpy.context.active_object
obj.name = "Cube_Generated"

# Create and apply material
mat = bpy.data.materials.new(name="cube_Material")
mat.use_nodes = True
bsdf = mat.node_tree.nodes["Principled BSDF"]
bsdf.inputs["Base Color"].default_value = (1, 0, 0, 1)  # Red

obj.data.materials.append(mat)

print(f"Created cube at location [0, 0, 0]")
"""

# Example 2: Complete Human Body
example_full_body = """
import bpy
import math

# Clear scene
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()

def create_full_body(location, detail_level):
    # Head
    bpy.ops.mesh.primitive_uv_sphere_add(radius=0.35, location=(location[0], location[1], location[2] + 6.5))
    head = bpy.context.active_object
    head.scale = (1, 0.85, 1.1)
    head.name = "Head"
    
    # Neck
    bpy.ops.mesh.primitive_cylinder_add(radius=0.15, depth=0.3, location=(location[0], location[1], location[2] + 6))
    neck = bpy.context.active_object
    neck.name = "Neck"
    
    # Torso
    bpy.ops.mesh.primitive_cube_add(size=2, location=(location[0], location[1], location[2] + 4.5))
    torso = bpy.context.active_object
    torso.scale = (0.8, 0.5, 1.5)
    torso.name = "Torso"
    
    # Arms
    for x_side in [-1.2, 1.2]:
        # Shoulder
        bpy.ops.mesh.primitive_uv_sphere_add(radius=0.2, location=(location[0] + x_side, location[1], location[2] + 5.5))
        shoulder = bpy.context.active_object
        shoulder.name = f"Shoulder_{'L' if x_side < 0 else 'R'}"
        
        # Upper arm
        bpy.ops.mesh.primitive_cylinder_add(radius=0.12, depth=1.2, location=(location[0] + x_side, location[1], location[2] + 4.5))
        upper_arm = bpy.context.active_object
        upper_arm.name = f"Upper_Arm_{'L' if x_side < 0 else 'R'}"
        
        # Forearm
        bpy.ops.mesh.primitive_cylinder_add(radius=0.1, depth=1, location=(location[0] + x_side, location[1], location[2] + 3.2))
        forearm = bpy.context.active_object
        forearm.name = f"Forearm_{'L' if x_side < 0 else 'R'}"
        
        # Hand
        bpy.ops.mesh.primitive_cube_add(size=0.3, location=(location[0] + x_side, location[1], location[2] + 2.5))
        hand = bpy.context.active_object
        hand.scale = (1.2, 0.5, 1.5)
        hand.name = f"Hand_{'L' if x_side < 0 else 'R'}"
    
    # Pelvis
    bpy.ops.mesh.primitive_cube_add(size=1, location=(location[0], location[1], location[2] + 3))
    pelvis = bpy.context.active_object
    pelvis.scale = (1, 0.6, 0.5)
    pelvis.name = "Pelvis"
    
    # Legs
    for x_side in [-0.4, 0.4]:
        # Thigh
        bpy.ops.mesh.primitive_cylinder_add(radius=0.15, depth=1.5, location=(location[0] + x_side, location[1], location[2] + 2))
        thigh = bpy.context.active_object
        thigh.name = f"Thigh_{'L' if x_side < 0 else 'R'}"
        
        # Calf
        bpy.ops.mesh.primitive_cylinder_add(radius=0.12, depth=1.3, location=(location[0] + x_side, location[1], location[2] + 0.5))
        calf = bpy.context.active_object
        calf.name = f"Calf_{'L' if x_side < 0 else 'R'}"
        
        # Foot
        bpy.ops.mesh.primitive_cube_add(size=0.3, location=(location[0] + x_side, location[1] + 0.15, location[2] - 0.3))
        foot = bpy.context.active_object
        foot.scale = (1, 2, 0.7)
        foot.name = f"Foot_{'L' if x_side < 0 else 'R'}"
    
    # Apply subdivision to main parts
    for obj_name in ["Head", "Torso"]:
        obj = bpy.data.objects.get(obj_name)
        if obj:
            mod = obj.modifiers.new(name="Subsurf", type='SUBSURF')
            mod.levels = 2

create_full_body((0, 0, 0), "medium")
print("Created full_body with medium detail")
"""

# Example 3: House
example_house = """
import bpy
import math

# Clear existing objects
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()

def create_house(location, floors, style):
    floor_height = 3.0
    
    # Create base/foundation
    bpy.ops.mesh.primitive_cube_add(size=2, location=(location[0], location[1], location[2] + 0.5))
    base = bpy.context.active_object
    base.scale = (4, 4, 0.5)
    base.name = "House_Base"
    
    # Create walls
    bpy.ops.mesh.primitive_cube_add(size=2, location=(location[0], location[1], location[2] + 2))
    walls = bpy.context.active_object
    walls.scale = (3.5, 3.5, 1.5)
    walls.name = "House_Walls"
    
    # Create roof
    bpy.ops.mesh.primitive_cone_add(vertices=4, radius1=5, depth=2, location=(location[0], location[1], location[2] + 5))
    roof = bpy.context.active_object
    roof.rotation_euler[2] = math.radians(45)
    roof.name = "House_Roof"
    
    # Create door
    bpy.ops.mesh.primitive_cube_add(size=1, location=(location[0] + 3.5, location[1], location[2] + 1.5))
    door = bpy.context.active_object
    door.scale = (0.1, 1, 1.5)
    door.name = "House_Door"
    
    # Create windows
    for i, pos in enumerate([(-2, 2, 2.5), (2, 2, 2.5), (-2, -2, 2.5), (2, -2, 2.5)]):
        bpy.ops.mesh.primitive_cube_add(size=0.8, location=(location[0] + pos[0], location[1] + pos[1], location[2] + pos[2]))
        window = bpy.context.active_object
        window.scale = (0.1, 1, 1)
        window.name = f"House_Window_{i}"

create_house((0, 0, 0), 1, "modern")
print("Created house with 1 floors")
"""

# Example 4: Church
example_church = """
import bpy
import math

# Clear existing objects
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()

def create_church(location, floors, style):
    floor_height = 3.0
    
    # Create church base
    bpy.ops.mesh.primitive_cube_add(size=2, location=(location[0], location[1], location[2] + 2))
    base = bpy.context.active_object
    base.scale = (4, 6, 2)
    base.name = "Church_Base"
    
    # Create tower
    bpy.ops.mesh.primitive_cube_add(size=2, location=(location[0], location[1] - 5, location[2] + 5))
    tower = bpy.context.active_object
    tower.scale = (1.5, 1.5, 3)
    tower.name = "Church_Tower"
    
    # Create spire
    bpy.ops.mesh.primitive_cone_add(radius1=1.8, depth=4, location=(location[0], location[1] - 5, location[2] + 10))
    spire = bpy.context.active_object
    spire.name = "Church_Spire"
    
    # Create cross on top
    bpy.ops.mesh.primitive_cube_add(size=0.3, location=(location[0], location[1] - 5, location[2] + 13))
    cross_v = bpy.context.active_object
    cross_v.scale = (1, 1, 3)
    cross_v.name = "Cross_Vertical"
    
    bpy.ops.mesh.primitive_cube_add(size=0.3, location=(location[0], location[1] - 5, location[2] + 12.5))
    cross_h = bpy.context.active_object
    cross_h.scale = (2, 1, 1)
    cross_h.name = "Cross_Horizontal"
    
    # Create entrance
    bpy.ops.mesh.primitive_cube_add(size=1, location=(location[0] + 4, location[1] + 2, location[2] + 1.5))
    entrance = bpy.context.active_object
    entrance.scale = (0.1, 1.5, 2)
    entrance.name = "Church_Entrance"

create_church((0, 0, 0), 1, "modern")
print("Created church with 1 floors")
"""

# Example 5: Applying Textures
example_texture = """
import bpy

# Get the object (assuming it exists)
obj = bpy.data.objects.get("Cube")

if obj is None:
    print("Error: Object 'Cube' not found")
else:
    # Create material
    mat = bpy.data.materials.new(name="wood_Material")
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    
    # Clear default nodes
    nodes.clear()
    
    # Create nodes
    output = nodes.new(type='ShaderNodeOutputMaterial')
    bsdf = nodes.new(type='ShaderNodeBsdfPrincipled')
    
    # Set material properties for wood
    bsdf.inputs["Base Color"].default_value = (0.4, 0.25, 0.1, 1)
    bsdf.inputs["Roughness"].default_value = 0.8
    bsdf.inputs["Metallic"].default_value = 0
    
    # Link nodes
    mat.node_tree.links.new(bsdf.outputs["BSDF"], output.inputs["Surface"])
    
    # Assign material to object
    if obj.data.materials:
        obj.data.materials[0] = mat
    else:
        obj.data.materials.append(mat)
    
    print("Applied wood texture to Cube")
"""

# How to use these examples in Blender:
"""
1. Open Blender
2. Switch to the "Scripting" workspace
3. Click "New" to create a new text block
4. Copy and paste one of the example scripts above
5. Click "Run Script" button or press Alt+P
6. The 3D objects will be created in your scene

Note: Some scripts clear the scene first, so save your work before running them.
"""
